<?php

"$$sql = \"SELECT * FROM `table name` WHERE id = ?;\";",
			"$$stmt = $$conn->prepare($$sql);",
			"",
			"if (!$$stmt) {",
			"// ! Handle the case where the prepared statement could not be created",
    		"header(\"Location: \");",
    		"exit;",
			"}",
			"",
			"$$stmt->bind_param(\"i\", $$id);",
			"",
			"// ? checks to see if the execute fails",
			"if (!$$stmt->execute()) {",
			"header(\"Location: \");",
    		"$$stmt->close();",
    		"exit;",
			"}",
			"",
			"// * Gets the Result",
			"$$result = $$stmt->get_result();",
			"",
			"if ($$result->num_rows > 0) {",
    		"while ($$row = $$result->fetch_assoc()) {",
        	"// * Your Code here",
        	"",
    		"}",
			"} else {",
    		"// ! No data found",
			"}"